-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 21:21:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema horakja19_1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `horakja19_1` ;

-- -----------------------------------------------------
-- Schema horakja19_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horakja19_1` DEFAULT CHARACTER SET utf8 ;
USE `horakja19_1` ;

-- -----------------------------------------------------
-- Table `horakja19_1`.`appeals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`appeals` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`appeals` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `takedownsID` INT NOT NULL,
  `message` VARCHAR(1024) NULL,
  `hasBeenRead` TINYINT(1) NOT NULL DEFAULT 0,
  `dateAdded` DATETIME NOT NULL DEFAULT NOW(),
  `hasBeenAccepted` TINYINT(1) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`comments` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`comments` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `websitesID` INT UNSIGNED NOT NULL,
  `usersID` INT UNSIGNED NOT NULL,
  `parentCommentID` INT UNSIGNED NULL,
  `timePosted` DATETIME NOT NULL DEFAULT NOW(),
  `content` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`media` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`media` (
  `src` CHAR(10) NOT NULL,
  `usersID` INT UNSIGNED NOT NULL,
  `basename` VARCHAR(200) NULL,
  `extension` VARCHAR(8) NULL,
  `mimeContentType` VARCHAR(100) NOT NULL,
  `timeCreated` DATETIME NOT NULL DEFAULT NOW(),
  `hash` CHAR(40) NOT NULL,
  `size` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`src`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`passwordRecoveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`passwordRecoveries` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`passwordRecoveries` (
  `passwordRecoveriesID` INT UNSIGNED NOT NULL,
  `urlArg` CHAR(32) NOT NULL,
  PRIMARY KEY (`passwordRecoveriesID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`pinnedComments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`pinnedComments` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`pinnedComments` (
  `commentsID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`commentsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`plannedWebsites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`plannedWebsites` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`plannedWebsites` (
  `websitesID` INT UNSIGNED NOT NULL,
  `releaseDate` DATETIME NOT NULL,
  PRIMARY KEY (`websitesID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`profilePictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`profilePictures` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`profilePictures` (
  `src` CHAR(10) NOT NULL,
  `usersID` INT UNSIGNED NOT NULL,
  `hash` CHAR(40) NOT NULL,
  `extension` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`src`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`reactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`reactions` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`reactions` (
  `commentsID` INT UNSIGNED NOT NULL,
  `usersID` INT UNSIGNED NOT NULL,
  `value` TINYINT(1) NOT NULL,
  PRIMARY KEY (`commentsID`, `usersID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`takedowns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`takedowns` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`takedowns` (
  `websitesID` INT UNSIGNED NOT NULL,
  `message` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`websitesID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`themes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`themes` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`themes` (
  `src` CHAR(10) NOT NULL,
  `usersID` INT UNSIGNED NULL DEFAULT 0,
  `name` VARCHAR(64) NOT NULL,
  `hash` CHAR(40) NOT NULL,
  PRIMARY KEY (`src`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`timeoutMails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`timeoutMails` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`timeoutMails` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usersID` INT UNSIGNED NOT NULL,
  `expires` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`users` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`users` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `themesSRC` CHAR(10) NULL,
  `email` VARCHAR(320) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `level` TINYINT(1) UNSIGNED NOT NULL,
  `website` VARCHAR(64) NOT NULL,
  `isVerified` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `isDisabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `username` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`verificationCodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`verificationCodes` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`verificationCodes` (
  `verificationCodesID` INT UNSIGNED NOT NULL,
  `code` CHAR(6) NOT NULL,
  PRIMARY KEY (`verificationCodesID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horakja19_1`.`websites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horakja19_1`.`websites` ;

CREATE TABLE IF NOT EXISTS `horakja19_1`.`websites` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `themesSRC` CHAR(10) NULL,
  `thumbnailSRC` CHAR(10) NULL,
  `usersID` INT UNSIGNED NOT NULL,
  `src` CHAR(10) NOT NULL,
  `timeCreated` DATETIME NOT NULL DEFAULT NOW(),
  `title` VARCHAR(64) NOT NULL,
  `isTemplate` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `isPublic` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `areCommentsAvailable` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `isHomepage` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `isTakenDown` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

USE `horakja19_1`;

DELIMITER $$

USE `horakja19_1`$$
DROP TRIGGER IF EXISTS `horakja19_1`.`takedowns_BEFORE_DELETE` $$
USE `horakja19_1`$$
CREATE DEFINER = CURRENT_USER TRIGGER `horakja19_1`.`takedowns_BEFORE_DELETE` BEFORE DELETE ON `takedowns` FOR EACH ROW
BEGIN
	DELETE FROM `appeals` WHERE `appeals`.takedownsID = OLD.websitesID;
END$$


USE `horakja19_1`$$
DROP TRIGGER IF EXISTS `horakja19_1`.`timeoutMails_BEFORE_DELETE` $$
USE `horakja19_1`$$
CREATE DEFINER = CURRENT_USER TRIGGER `horakja19_1`.`timeoutMails_BEFORE_DELETE` BEFORE DELETE ON `timeoutMails` FOR EACH ROW
BEGIN
	DELETE FROM `passwordRecoveries` WHERE `passwordRecoveries`.passwordRecoveriesID = OLD.ID;
    DELETE FROM `verificationCodes` WHERE `verificationCodes`.verificationCodesID = OLD.ID;
END$$


USE `horakja19_1`$$
DROP TRIGGER IF EXISTS `horakja19_1`.`websites_BEFORE_DELETE` $$
USE `horakja19_1`$$
CREATE DEFINER = CURRENT_USER TRIGGER `horakja19_1`.`websites_BEFORE_DELETE` BEFORE DELETE ON `websites` FOR EACH ROW
BEGIN

END
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
