-- MySQL Script generated by MySQL Workbench
-- Wed Sep  7 17:08:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nocoma
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nocoma` ;

-- -----------------------------------------------------
-- Schema nocoma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nocoma` DEFAULT CHARACTER SET utf8 ;
USE `nocoma` ;

-- -----------------------------------------------------
-- Table `nocoma`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`comments` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`comments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `websitesID` INT NOT NULL,
  `parentCommentID` INT NULL,
  `timePosted` DATETIME NOT NULL,
  `content` TEXT NOT NULL,
  `score` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `nocoma`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`media` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`media` (
  `src` VARCHAR(128) NOT NULL,
  `extension` VARCHAR(8) NULL,
  `basename` VARCHAR(200) NULL,
  PRIMARY KEY (`src`),
  UNIQUE INDEX `src_UNIQUE` (`src` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `nocoma`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`users` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `profileSRC` VARCHAR(128) NOT NULL,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `level` TINYINT(1) NOT NULL,
  `website` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `usersID_UNIQUE` (`ID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `nocoma`.`websites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`websites` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`websites` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `usersID` INT NOT NULL,
  `thumbnailSRC` VARCHAR(128) NOT NULL,
  `timeCreated` DATETIME NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `description` VARCHAR(256) NULL,
  `isPublic` TINYINT(1) NOT NULL,
  `templateStyle` TINYINT(1) NOT NULL,
  `areCommentsEnabled` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
