-- MySQL Script generated by MySQL Workbench
-- Sun Sep 11 12:35:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nocoma
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nocoma` ;

-- -----------------------------------------------------
-- Schema nocoma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nocoma` DEFAULT CHARACTER SET utf8 ;
USE `nocoma` ;

-- -----------------------------------------------------
-- Table `nocoma`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`comments` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`comments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `websitesID` INT NOT NULL,
  `parentCommentID` INT NULL,
  `timePosted` DATETIME NOT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `nocoma`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`media` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`media` (
  `src` VARCHAR(10) NOT NULL,
  `extension` VARCHAR(8) NULL,
  `basename` VARCHAR(200) NULL,
  PRIMARY KEY (`src`),
  UNIQUE INDEX `src_UNIQUE` (`src` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `nocoma`.`passwordRecoveries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`passwordRecoveries` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`passwordRecoveries` (
  `passwordRecoveriesID` INT NOT NULL,
  `urlArg` CHAR(32) NOT NULL,
  PRIMARY KEY (`passwordRecoveriesID`));


-- -----------------------------------------------------
-- Table `nocoma`.`themes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`themes` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`themes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `nocoma`.`timeoutMails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`timeoutMails` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`timeoutMails` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `usersID` INT NOT NULL,
  `expires` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `nocoma`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`users` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `themesID` INT NOT NULL,
  `profileSRC` VARCHAR(10) NULL,
  `email` VARCHAR(320) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `level` TINYINT NOT NULL,
  `website` VARCHAR(64) NOT NULL,
  `isVerified` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `usersID_UNIQUE` (`ID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `nocoma`.`verificationCodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`verificationCodes` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`verificationCodes` (
  `verificationCodesID` INT NOT NULL,
  `code` CHAR(6) NOT NULL,
  PRIMARY KEY (`verificationCodesID`));


-- -----------------------------------------------------
-- Table `nocoma`.`websites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nocoma`.`websites` ;

CREATE TABLE IF NOT EXISTS `nocoma`.`websites` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `usersID` INT NOT NULL,
  `thumbnailSRC` VARCHAR(10) NOT NULL,
  `timeCreated` DATETIME NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `description` VARCHAR(256) NULL,
  `templateStyle` TINYINT NOT NULL,
  `isPublic` TINYINT NOT NULL,
  `areCommentsAvailable` TINYINT NOT NULL,
  `isHomepage` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);

USE `nocoma`;

DELIMITER $$

USE `nocoma`$$
DROP TRIGGER IF EXISTS `nocoma`.`timeoutMails_BEFORE_DELETE` $$
USE `nocoma`$$
CREATE DEFINER = CURRENT_USER TRIGGER `nocoma`.`timeoutMails_BEFORE_DELETE` BEFORE DELETE ON `timeoutMails` FOR EACH ROW
BEGIN
	DELETE FROM `passwordrecoveries` WHERE `passwordrecoveries`.passwordRecoveriesID = OLD.ID;
    DELETE FROM `verificationcodes` WHERE `verificationcodes`.verificationCodesID = OLD.ID;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
